language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 5e823d8f06d3ef8dbb30133be59c53f1abafbbc3
 local_dir: dist
 on:
   branch: master
